[package]
name = "rabid-remote"
version = "0.1.0"
authors = ["Diez B. Roggisch <deets@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = ""
